FROM ubuntu:16.04
MAINTAINER Elliott Slaughter <slaughter@cs.stanford.edu>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq && \
    apt-get install -qq build-essential bzip2 curl libdigest-sha-perl git zlib1g-dev && \
    apt-get clean

ENV SIT_ARCH x86_64-rhel7-gcc48-opt
ENV CONDA_PREFIX /conda
ENV PATH $CONDA_PREFIX/bin:$PATH
ENV LD_LIBRARY_PATH $CONDA_PREFIX/lib:$LD_LIBRARY_PATH

# https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
RUN curl -O https://repo.continuum.io/miniconda/Miniconda2-4.3.21-Linux-x86_64.sh && \
    echo "b87adda9eb41f3ae6c2999fda739ab61ebb3892e  Miniconda2-4.3.21-Linux-x86_64.sh" | shasum --check && \
    /bin/bash Miniconda2-4.3.21-Linux-x86_64.sh -b -p "$CONDA_PREFIX" && \
    conda update -y conda && \
    conda install -y scons cython libtiff=4.0.6 icu=54 && \
    conda install -y --channel lcls-rhel7 psana-conda ndarray && \
    conda uninstall --force mpich2 && \
    rm Miniconda2-4.3.21-Linux-x86_64.sh
